import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Alert from '@/components/Alert';
import { AppContextProvider } from '@/components/AppContext';
import LoadingOverlay from '@/components/LoadingOverlay';
import ThemeRegistry from '@/components/ThemeRegistry';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} style={{ colorScheme: 'dark' }}>
      <body>
        <ThemeRegistry>
          <AppContextProvider>
            <LoadingOverlay />
            {children}
            <Alert />
          </AppContextProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
